#!/usr/bin/env bash
# pinging network utility use to test if the receiving network device is reachable
if [ $# -eq 0 ]; then

	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi
ping -c 5 "$1"
