#!/usr/bin/env bash
#Using if else and elif
var='Best School'
count=0
while [ $count -lt 10 ]
do
	if [ $count -eq 3 ]; then
		echo "bad luck"
	elif [ $count -eq 7 ]; then
		echo "good luck"
	else
		echo "$var"
	fi
	((count++))
done
