#!/usr/bin/env bash
#bad and good lucks
count=1
while [ $count -le 20 ]
do
	echo "$count"
	if [ $count -eq 4 ]; then
		echo "bad luck from china"
	elif [ $count -eq 9 ]; then
		echo "bad luck from japan"
	elif [ $count -eq 17 ]; then
		echo "bad luck from italy"
	fi
	((count++))
done
